### ISSUE TITLE
safe close()?

### ISSUE THREAD

**Issue by belm0** [python-hyper/wsproto#59]
WSConnection.close() calls a method on self._proto, but that attribute is only non-null in certain states.

https://github.com/python-hyper/wsproto/blob/8fb410a2686f4c07c248c11cb6b387f28c7519c8/wsproto/connection.py#L189

I don't see a public API to test for other than CLOSED state, so caller of close() doesn't have a straightforward way to safeguard.  Probably best to have close() return early if not in a suitable state.

**Comment by belm0** [comment]
This happens routinely, such as when the WSConnection is managed by a context manager and you ctrl-C before the handshake.

Reiterating, but my vote is for `close()` to return early if not in a suitable state, no exceptions involved.  It seems the least error-prone for users, and would also provide idempotentcy.

**Comment by njsmith** [comment]
> This happens routinely, such as when the WSConnection is managed by a context manager and you ctrl-C before the handshake.

I assume you mean in the asyncwebsockets project specifically? (https://github.com/Fuyukai/asyncwebsockets/issues/9) You may be right that wsproto should fix this on its side, but I like to understand the problem before committing to things like that :-). For example, maybe it would be better for asyncwebsockets to be careful not to call `WSConnection.close()` until after the handshake.

It's not entirely clear that idempotency makes sense for websocket `close` (at least at the wsproto level), because in the websocket protocol, `close` actually sends a message, which has an attached error code and a free-form text field. So what if someone calls `close` twice with two different error codes? We can't send two close packets.

Though... right now if someone calls `close` twice, it *does* try to send two close packets, because there's nothing enforcing that you can't call `close` when already in state `CLOSED`. I guess that's a bug too.

This also makes me a bit nervous about making it so that `close` silently succeed when you call it before the handshake completes – if you gave us an error code and reason to send, and we didn't actually send them... maybe we shouldn't just silently pretend we did?

OTOH, the whole clean shutdown machinery for websockets is intrinsically kind of unreliable, because you have to be prepared to handle a network drop at any moment. There's no guarantee that a close packet actually arrives anyway – the network might eat it. And IIRC there are popular websocket implementations that don't even bother with sending close packets and just kill the connection when they're done. So maybe this is over-fussy and we should just treat `close` as best-effort.

**Comment by belm0** [comment]
> For example, maybe it would be better for asyncwebsockets to be careful not to call WSConnection.close() until after the handshake.

I don't think it can be implemented on the current WSConnection API without race conditions.  E.g. if there is a cancel between when WSConnection gets the handshake internally and the context manager sets a `got_handshake` variable to be used in finalization.

**Comment by njsmith** [comment]
Since `WSConnection` is a pure sans-io object, it doesn't have cancellation, and race-conditions aren't really a thing. However, it does look like for clients it's pretty opaque from the outside when exactly a connection has transitioned into the state where you can call `close`: I think the rule is "it happens in whichever call to `receive_bytes` changes the internal state such that you could immediately call `events` and get back a `ConnectionEstablished` event". *Technically* it's possible to detect this so long as you always call `events` after `receive_bytes` (which most people probably do!), but it does seem a bit unreasonable.

**Comment by Kriechi** [comment]
@belm0 does the recently merged #50 help you?
One alternative would be to make `close()` simply do nothing if it is not yet in a state where it can send a close frame.

**Comment by mehaase** [comment]
If closing can fail silently, then the API creates the following trap:

```
conn.close()
wait_for_closing_handshake()
```

The user wants to initiate a closing handshake and then wait for the other side to complete the handshake. If the opening handshake isn't complete and this code fails silently, then this code hangs forever.

Raising an exception sounds like the best option to me.

**Comment by mehaase** [comment]
The two simplest options:

1) Expose a read-only connection state property. The caller can check if the connection is open before calling `close()`.
2) Raise a better exception. Instead of `AttributeError`, create a more specific exception class, like `ConnectionStateError` (possibly includes the current connection state, if there is no public state property).

These aren't mutually exclusive, of course. I'd prefer to have both of them, but either one is enough to solve this issue.

**Comment by touilleMan** [comment]
After some time figuring out this `AttributeError` exception, I've ended up here :smile: 

So here is PR #92 implementing the solution exposed by @mehaase

**Comment by pgjones** [comment]
I think this is complete with 2b38d3a7c0ebcb6eea39f00c4ab2137371fe3474.
